### ISSUE TITLE
Floating Label sits in input on autofilled password fields (Chrome)

### ISSUE THREAD

**Issue by michael-jahn-dev** [Baedda/floating-form-labels#12]
On page load, floating form labels fails to detect auto filled in password fields in chrome. The label only floats above the field when you do any sort of input to the page (eg. pressing a key or clicking anywhere in the body)
![bug](https://cloud.githubusercontent.com/assets/3817545/24599672/8d6c9a6e-1851-11e7-82b5-a9d7b8ef569c.PNG)

**Comment by alexanderbuerner** [comment]
Same bug :(

**Comment by michael-jahn-dev** [comment]
@Baedda Any news on this? :)

**Comment by artursopelnik** [comment]
Try to check initial for `$element.is('*:-webkit-autofill')` 
Otherwise [observe ](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver)input field for webkit-autofill.

**Comment by Baedda** [comment]
@Miw0 could you also have a look at this newest commit to #18 
https://github.com/Baedda/floating-form-labels/pull/18/commits/fdeec0a5e18a6a427191fc833223d18440dc617b
as I would merge this now to finally fix this issue. I have a feeling that @artursopelnik should have a look at it, too? 

Personally I find addressing webkit specially is not the best solution but there doesn't seem to be a better one. Also the try/catch around that line to catch crossbrowser issues really makes me feel bad but I understand that this fix is really important. So I am waiting for your "go" and I will merge this.

**Comment by michael-jahn-dev** [comment]
@Baedda hau rin den kram ;)

**Comment by Baedda** [comment]
Should be fixed with https://github.com/Baedda/floating-form-labels/commit/5dc792f0e68415307501ff82a1b9834bec6b842a. I come up with v1.2.3 in a few minutes.

**Comment by michael-jahn-dev** [comment]
@Baedda sorry but this didn't fix the issue :(

I found out that it has to be a problem with timing. When using `setTimeout` to delay calling your toggleClass method, it seems to work consistent.

```javascript
setTimeout(function () {
  this._toggleClass(this._isWebkitAutofilled());
}.bind(this), 1000);
```

**Comment by Baedda** [comment]
Hmm this drives me really crazy. I guess that Chrome autofills the inputs asynchronous to the page rendering. This is why we can not rely on `this.el.find(':-webkit-autofill').length > 0` as a condition because if the JavaScript is faster then the autofilling process, then the JS won't find any autofilled field. I think that other browsers autofill the fields while rendering. This is why the JavaScript always detects the prefilled value.

**Comment by michael-jahn-dev** [comment]
@Baedda Please revert this commit because calling 2x `this._toggleClass()` in order makes pre-filled inputs fail to correctly float the label.

**Comment by artursopelnik** [comment]
@Miw0 +1
Please revert this commit, we have to look for a better solution.

**Comment by michael-jahn-dev** [comment]
@artursopelnik I reverted #18 and published `v1.2.4`.

**Comment by marhalpert** [comment]
This is my work around:

1. I moved the `label` under the `input`

```HTML
  <div class="ffl-wrapper">
    <input type="text" id="name" name="name">
    <label for="name" class="ffl-label">Name</label>
  </div>
```
2. I added these styles

```CSS
.ffl-floated input:-webkit-autofill +  .ffl-label {
  .....your floating label styles here
}
```

**Comment by Baedda** [comment]
This is indeed a real good work around. But we can not rely on this solution inside ffl itself because we want to stay markup agnostic and support every possible html structure. 
But again: this really might help until we find a way to detect autofill via JavaScript. Thank you very much @marhalpert!

**Comment by Baedda** [comment]
Now there is even an article posted in the smashing magazine newsletter that addresses the exact same problem that we have.

https://medium.com/@brunn/detecting-autofilled-fields-in-javascript-aed598d25da7

In this article they use the hack @apriljunge wanted us to merge at the very beginning of this issue. So I believe that there is no other workaround for Chrome.

**Comment by apriljunge** [comment]
The PR you mentioned is #13. In the meantime it got a bit outdated.
If you want I can rebase and pass it in again.

The arguments why you didn't want to merge haven't changed ;)

**Comment by artursopelnik** [comment]
Vielleicht wäre dieser Hack ein interessanter Umweg:

**CSS:**
`input:-webkit-autofill {
     content: "autofill";
}`

**JS:**
`if (this.input.css('content') === 'autofill')`

Das sollte aufjedenfall funktioniert und kann gerne bei Bedarf ausprobiert werden. 
Eventuell muss aber noch die Prüfung verzögert werden (bei Timing-Problemen).

**Comment by luckylooke** [comment]
This is how google solved it :)
![Screenshot at Jun 10 07-23-32](https://user-images.githubusercontent.com/3660030/59492339-0c53e800-8e89-11e9-94d0-cc8702ce8df7.png)

**Comment by Baedda** [comment]
Haha thank you so much for this screenshot @luckylooke

**Comment by tomm1996** [comment]
@luckylooke this is gold

**Comment by luckylooke** [comment]
Btw.. I have fixed my login with styles applied on `:-webkit-autofill` :)

**Comment by pgangwani** [comment]
This seems to be helping me out
```
if($element.matches(':-webkit-autofill')) { 
  console.log('write animating label css')
}
```

**Comment by Baedda** [comment]
Has anyone checked if it works with the (new) native :autofill Attribute?
https://developer.mozilla.org/en-US/docs/Web/CSS/:autofill

**Comment by Rickyoung221** [comment]
> This is my work around:
> 
> 1. I moved the `label` under the `input`
> 
> ```
>   <div class="ffl-wrapper">
>     <input type="text" id="name" name="name">
>     <label for="name" class="ffl-label">Name</label>
>   </div>
> ```
> 
> 2. I added these styles
> 
> ```css
> .ffl-floated input:-webkit-autofill +  .ffl-label {
>   .....your floating label styles here
> }
> ```

I am developing a React project and I used Bootstrap in it. And I met the same issue. Does anyone know how to use it in React?

**Comment by REACT-DEVELOPER-IBROKHIM** [comment]
> Same bug :(

input:-webkit-autofill + label

**Comment by apriljunge** [comment]
```css
.ffl-wrapper:has(input:-webkit-autofill) .ffl-label {
    // Code here
}
```
This does the same and is markup agnostic. [Demo](https://codepen.io/apriljunge/pen/vYraMpv)

**Comment by mykuldbg** [comment]
this code here worked fine for me just have to add it to my cade then edit the class name
  <div class="ffl-wrapper">
    <input type="text" id="name" name="name">
    <label for="name" class="ffl-label">Name</label>
  </div>
///
.ffl-floated input:-webkit-autofill +  .ffl-label {
  .....your floating label styles here
}
